-- Code generated by sdm. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS pii_invoices (
  invoice_id TEXT,
  seller_gst TEXT,
  buyer_gst TEXT,
  metadata JSONB,
  PRIMARY KEY (invoice_id),
  FOREIGN KEY (seller_id) REFERENCES pii_users(id),
  FOREIGN KEY (buyer_id) REFERENCES pii_users(id)
);

CREATE TABLE IF NOT EXISTS chain_invoices (
  key TEXT NOT NULL,
  field_name TEXT NOT NULL,
  version BIGINT NOT NULL,
  tx_hash TEXT,
  field_value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key, field_name, version)
);

CREATE OR REPLACE FUNCTION chain_invoices_set_version()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.version IS NULL OR NEW.version = 0 THEN
    NEW.version := COALESCE(
      (SELECT MAX(version) FROM chain_invoices WHERE key = NEW.key AND field_name = NEW.field_name),
      0
    ) + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS chain_invoices_set_version_trigger ON chain_invoices;
CREATE TRIGGER chain_invoices_set_version_trigger
BEFORE INSERT ON chain_invoices
FOR EACH ROW EXECUTE FUNCTION chain_invoices_set_version();

CREATE OR REPLACE VIEW invoices AS
  SELECT
    p.invoice_id,
    p.seller_gst,
    c_hashed_seller_gst.field_value AS hashed_seller_gst,
    p.buyer_gst,
    c_hashed_buyer_gst.field_value AS hashed_buyer_gst,
    c_seller_id.field_value AS seller_id,
    c_buyer_id.field_value AS buyer_id,
    c_amount.field_value AS amount,
    p.metadata,
    c_price.field_value::jsonb AS price
  FROM pii_invoices p
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='hashed_seller_gst' ORDER BY key, field_name, version DESC) c_hashed_seller_gst ON p.invoice_id = c_hashed_seller_gst.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='hashed_buyer_gst' ORDER BY key, field_name, version DESC) c_hashed_buyer_gst ON p.invoice_id = c_hashed_buyer_gst.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='seller_id' ORDER BY key, field_name, version DESC) c_seller_id ON p.invoice_id = c_seller_id.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='buyer_id' ORDER BY key, field_name, version DESC) c_buyer_id ON p.invoice_id = c_buyer_id.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='amount' ORDER BY key, field_name, version DESC) c_amount ON p.invoice_id = c_amount.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='price' ORDER BY key, field_name, version DESC) c_price ON p.invoice_id = c_price.key
;

