-- Code generated by sdm. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS pii_invoices (
  invoice_id TEXT,
  seller_gst TEXT,
  buyer_gst TEXT,
  seller_id TEXT,
  buyer_id TEXT,
  price JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP WITH TIME ZONE NULL,
  PRIMARY KEY (invoice_id),
  FOREIGN KEY (seller_id) REFERENCES pii_users(user_id),
  FOREIGN KEY (buyer_id) REFERENCES pii_users(user_id)
);

CREATE TABLE IF NOT EXISTS chain_invoices (
  key TEXT NOT NULL,
  field_name TEXT NOT NULL,
  version BIGINT NOT NULL,
  tx_hash TEXT,
  field_value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key, field_name, version)
);

CREATE OR REPLACE FUNCTION chain_invoices_set_version()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.version IS NULL OR NEW.version = 0 THEN
    NEW.version := COALESCE(
      (SELECT MAX(version) FROM chain_invoices WHERE key = NEW.key AND field_name = NEW.field_name),
      0
    ) + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS chain_invoices_set_version_trigger ON chain_invoices;
CREATE TRIGGER chain_invoices_set_version_trigger
BEFORE INSERT ON chain_invoices
FOR EACH ROW EXECUTE FUNCTION chain_invoices_set_version();

CREATE OR REPLACE VIEW invoices AS
  SELECT
    p.invoice_id,
    p.seller_gst,
    c_hashed_seller_gst.field_value AS hashed_seller_gst,
    p.buyer_gst,
    c_hashed_buyer_gst.field_value AS hashed_buyer_gst,
    p.seller_id,
    p.buyer_id,
    c_amount.field_value AS amount,
    c_metadata.field_value::jsonb AS metadata,
    p.price,
    c_tags.field_value AS tags,
    c_items.field_value::jsonb AS items,
    c_transfer_date.field_value::timestamptz AS transfer_date,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    c_tx.tx_hash
  FROM pii_invoices p
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='hashed_seller_gst' ORDER BY key, field_name, version DESC) c_hashed_seller_gst ON p.invoice_id = c_hashed_seller_gst.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='hashed_buyer_gst' ORDER BY key, field_name, version DESC) c_hashed_buyer_gst ON p.invoice_id = c_hashed_buyer_gst.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='amount' ORDER BY key, field_name, version DESC) c_amount ON p.invoice_id = c_amount.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='metadata' ORDER BY key, field_name, version DESC) c_metadata ON p.invoice_id = c_metadata.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='tags' ORDER BY key, field_name, version DESC) c_tags ON p.invoice_id = c_tags.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='items' ORDER BY key, field_name, version DESC) c_items ON p.invoice_id = c_items.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_invoices WHERE field_name='transfer_date' ORDER BY key, field_name, version DESC) c_transfer_date ON p.invoice_id = c_transfer_date.key
  LEFT JOIN (SELECT DISTINCT ON (key) key, tx_hash FROM chain_invoices ORDER BY key, version DESC) c_tx ON p.invoice_id = c_tx.key
;

