-- Code generated by sdm. DO NOT EDIT.

CREATE TABLE IF NOT EXISTS pii_users (
  id BIGSERIAL,
  user_id TEXT,
  email TEXT,
  name TEXT,
  PRIMARY KEY (id),
  UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS chain_users (
  key TEXT NOT NULL,
  field_name TEXT NOT NULL,
  version BIGINT NOT NULL,
  tx_hash TEXT,
  field_value TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key, field_name, version)
);

CREATE OR REPLACE FUNCTION chain_users_set_version()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.version IS NULL OR NEW.version = 0 THEN
    NEW.version := COALESCE(
      (SELECT MAX(version) FROM chain_users WHERE key = NEW.key AND field_name = NEW.field_name),
      0
    ) + 1;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS chain_users_set_version_trigger ON chain_users;
CREATE TRIGGER chain_users_set_version_trigger
BEFORE INSERT ON chain_users
FOR EACH ROW EXECUTE FUNCTION chain_users_set_version();

CREATE OR REPLACE VIEW users AS
  SELECT
    p.id,
    p.user_id,
    p.email,
    c_hashed_email.field_value AS hashed_email,
    p.name,
    c_pan.field_value AS pan,
    c_country.field_value AS country
  FROM pii_users p
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_users WHERE field_name='hashed_email' ORDER BY key, field_name, version DESC) c_hashed_email ON p.user_id = c_hashed_email.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_users WHERE field_name='pan' ORDER BY key, field_name, version DESC) c_pan ON p.user_id = c_pan.key
  LEFT JOIN (SELECT DISTINCT ON (key, field_name) field_value, key FROM chain_users WHERE field_name='country' ORDER BY key, field_name, version DESC) c_country ON p.user_id = c_country.key
;

