// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoice/invoice.proto

package invoice

import (
	_ "github.com/jinuthankachan/sdm/sdmprotos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber int64                  `protobuf:"varint,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	SellerGst     string                 `protobuf:"bytes,3,opt,name=seller_gst,json=sellerGst,proto3" json:"seller_gst,omitempty"`
	BuyerGst      string                 `protobuf:"bytes,4,opt,name=buyer_gst,json=buyerGst,proto3" json:"buyer_gst,omitempty"`
	SellerName    string                 `protobuf:"bytes,5,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	BuyerName     string                 `protobuf:"bytes,6,opt,name=buyer_name,json=buyerName,proto3" json:"buyer_name,omitempty"`
	Seller        string                 `protobuf:"bytes,7,opt,name=seller,proto3" json:"seller,omitempty"`
	Buyer         string                 `protobuf:"bytes,8,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Amount        int64                  `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_invoice_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_invoice_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invoice) GetInvoiceNumber() int64 {
	if x != nil {
		return x.InvoiceNumber
	}
	return 0
}

func (x *Invoice) GetSellerGst() string {
	if x != nil {
		return x.SellerGst
	}
	return ""
}

func (x *Invoice) GetBuyerGst() string {
	if x != nil {
		return x.BuyerGst
	}
	return ""
}

func (x *Invoice) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *Invoice) GetBuyerName() string {
	if x != nil {
		return x.BuyerName
	}
	return ""
}

func (x *Invoice) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *Invoice) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *Invoice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_invoice_invoice_proto protoreflect.FileDescriptor

const file_invoice_invoice_proto_rawDesc = "" +
	"\n" +
	"\x15invoice/invoice.proto\x12\ainvoice\x1a!proto/sdmprotos/annotations.proto\"\xb6\x02\n" +
	"\aInvoice\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\x80\xb5\x18\x01\x88\xb5\x18\x01R\x02id\x12/\n" +
	"\x0einvoice_number\x18\x02 \x01(\x03B\b\x90\xb5\x18\x01\x98\xb5\x18\x01R\rinvoiceNumber\x12'\n" +
	"\n" +
	"seller_gst\x18\x03 \x01(\tB\b\x90\xb5\x18\x01\xa0\xb5\x18\x01R\tsellerGst\x12%\n" +
	"\tbuyer_gst\x18\x04 \x01(\tB\b\x90\xb5\x18\x01\xa0\xb5\x18\x01R\bbuyerGst\x12%\n" +
	"\vseller_name\x18\x05 \x01(\tB\x04\x90\xb5\x18\x01R\n" +
	"sellerName\x12#\n" +
	"\n" +
	"buyer_name\x18\x06 \x01(\tB\x04\x90\xb5\x18\x01R\tbuyerName\x12\x16\n" +
	"\x06seller\x18\a \x01(\tR\x06seller\x12\x14\n" +
	"\x05buyer\x18\b \x01(\tR\x05buyer\x12\x16\n" +
	"\x06amount\x18\t \x01(\x03R\x06amountB\x15Z\x13demo/models/invoiceb\x06proto3"

var (
	file_invoice_invoice_proto_rawDescOnce sync.Once
	file_invoice_invoice_proto_rawDescData []byte
)

func file_invoice_invoice_proto_rawDescGZIP() []byte {
	file_invoice_invoice_proto_rawDescOnce.Do(func() {
		file_invoice_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoice_invoice_proto_rawDesc), len(file_invoice_invoice_proto_rawDesc)))
	})
	return file_invoice_invoice_proto_rawDescData
}

var file_invoice_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_invoice_invoice_proto_goTypes = []any{
	(*Invoice)(nil), // 0: invoice.Invoice
}
var file_invoice_invoice_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_invoice_invoice_proto_init() }
func file_invoice_invoice_proto_init() {
	if File_invoice_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoice_invoice_proto_rawDesc), len(file_invoice_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoice_invoice_proto_goTypes,
		DependencyIndexes: file_invoice_invoice_proto_depIdxs,
		MessageInfos:      file_invoice_invoice_proto_msgTypes,
	}.Build()
	File_invoice_invoice_proto = out.File
	file_invoice_invoice_proto_goTypes = nil
	file_invoice_invoice_proto_depIdxs = nil
}
