// Code generated by sdm. DO NOT EDIT.

package invoice

import (
	"time"
	"gorm.io/datatypes"
	"github.com/lib/pq"
	"gorm.io/gorm"
)

type InvoicePii struct {
	InvoiceId string    `gorm:"column:invoice_id;primaryKey"`
	SellerGst string    `gorm:"column:seller_gst"`
	BuyerGst  string    `gorm:"column:buyer_gst"`
	SellerId  string    `gorm:"column:seller_id"`
	BuyerId   string    `gorm:"column:buyer_id"`
	Price     *Money    `gorm:"column:price;type:jsonb;serializer:protojson"`
	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime"`
	UpdatedAt time.Time `gorm:"column:updated_at;autoUpdateTime"`
	IsDeleted bool      `gorm:"column:is_deleted;default:false"`
}

type InvoiceChain struct {
	Key        string    `gorm:"primaryKey;column:key"`
	FieldName  string    `gorm:"primaryKey;column:field_name"`
	Version    int64     `gorm:"primaryKey;column:version;autoIncrement"`
	TxHash     string    `gorm:"column:tx_hash"`
	FieldValue string    `gorm:"column:field_value"`
	CreatedAt  time.Time `gorm:"column:created_at"`
}

type InvoiceView struct {
	InvoiceId       string         `gorm:"column:invoice_id"`
	SellerGst       string         `gorm:"column:seller_gst"`
	HashedSellerGst string         `gorm:"column:hashed_seller_gst"`
	BuyerGst        string         `gorm:"column:buyer_gst"`
	HashedBuyerGst  string         `gorm:"column:hashed_buyer_gst"`
	SellerId        string         `gorm:"column:seller_id"`
	BuyerId         string         `gorm:"column:buyer_id"`
	Amount          int64          `gorm:"column:amount"`
	Metadata        datatypes.JSON `gorm:"column:metadata"`
	Price           *Money         `gorm:"column:price;serializer:protojson"`
	Tags            pq.StringArray `gorm:"column:tags;type:text[]"`
	CreatedAt       time.Time      `gorm:"column:created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at"`
	IsDeleted       bool           `gorm:"column:is_deleted"`
	TxHash          string         `gorm:"column:tx_hash"`
}

func (InvoicePii) TableName() string   { return "pii_invoices" }
func (InvoiceChain) TableName() string { return "chain_invoices" }
func (InvoiceView) TableName() string  { return "invoices" }

func (c *InvoiceChain) EnsureUnique(tx *gorm.DB) bool {
	var count int64
	err := tx.Model(&InvoiceChain{}).Where("field_name = ? AND field_value = ?", c.FieldName, c.FieldValue).Count(&count).Error
	if err != nil {
		return false
	}
	return count == 0
}
