// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoice/invoice.proto

package invoice

import (
	_ "github.com/jinuthankachan/sdm/sdmprotos"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	SellerGst     string                 `protobuf:"bytes,2,opt,name=seller_gst,json=sellerGst,proto3" json:"seller_gst,omitempty"`
	BuyerGst      string                 `protobuf:"bytes,3,opt,name=buyer_gst,json=buyerGst,proto3" json:"buyer_gst,omitempty"`
	SellerId      string                 `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	BuyerId       string                 `protobuf:"bytes,5,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Price         *Money                 `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Tags          []string               `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_invoice_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_invoice_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *Invoice) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *Invoice) GetSellerGst() string {
	if x != nil {
		return x.SellerGst
	}
	return ""
}

func (x *Invoice) GetBuyerGst() string {
	if x != nil {
		return x.BuyerGst
	}
	return ""
}

func (x *Invoice) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Invoice) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *Invoice) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Invoice) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Invoice) GetPrice() *Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Invoice) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int64                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Unit          string                 `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_invoice_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_invoice_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *Money) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Money) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

var File_invoice_invoice_proto protoreflect.FileDescriptor

const file_invoice_invoice_proto_rawDesc = "" +
	"\n" +
	"\x15invoice/invoice.proto\x12\ainvoice\x1a!proto/sdmprotos/annotations.proto\"\xdc\x02\n" +
	"\aInvoice\x12'\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tB\b\x80\xb5\x18\x01\x88\xb5\x18\x01R\tinvoiceId\x12'\n" +
	"\n" +
	"seller_gst\x18\x02 \x01(\tB\b\x90\xb5\x18\x01\xa0\xb5\x18\x01R\tsellerGst\x12%\n" +
	"\tbuyer_gst\x18\x03 \x01(\tB\b\x90\xb5\x18\x01\xa0\xb5\x18\x01R\bbuyerGst\x12-\n" +
	"\tseller_id\x18\x04 \x01(\tB\x10\xb2\xb5\x18\fUser.user_idR\bsellerId\x12+\n" +
	"\bbuyer_id\x18\x05 \x01(\tB\x10\xb2\xb5\x18\fUser.user_idR\abuyerId\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x12 \n" +
	"\bmetadata\x18\a \x01(\tB\x04\xc0\xb5\x18\x01R\bmetadata\x12.\n" +
	"\x05price\x18\b \x01(\v2\x0e.invoice.MoneyB\b\x90\xb5\x18\x01\xc0\xb5\x18\x01R\x05price\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\"1\n" +
	"\x05Money\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x03R\x05value\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\tR\x04unitB\x15Z\x13demo/models/invoiceb\x06proto3"

var (
	file_invoice_invoice_proto_rawDescOnce sync.Once
	file_invoice_invoice_proto_rawDescData []byte
)

func file_invoice_invoice_proto_rawDescGZIP() []byte {
	file_invoice_invoice_proto_rawDescOnce.Do(func() {
		file_invoice_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoice_invoice_proto_rawDesc), len(file_invoice_invoice_proto_rawDesc)))
	})
	return file_invoice_invoice_proto_rawDescData
}

var file_invoice_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_invoice_invoice_proto_goTypes = []any{
	(*Invoice)(nil), // 0: invoice.Invoice
	(*Money)(nil),   // 1: invoice.Money
}
var file_invoice_invoice_proto_depIdxs = []int32{
	1, // 0: invoice.Invoice.price:type_name -> invoice.Money
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_invoice_invoice_proto_init() }
func file_invoice_invoice_proto_init() {
	if File_invoice_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoice_invoice_proto_rawDesc), len(file_invoice_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoice_invoice_proto_goTypes,
		DependencyIndexes: file_invoice_invoice_proto_depIdxs,
		MessageInfos:      file_invoice_invoice_proto_msgTypes,
	}.Build()
	File_invoice_invoice_proto = out.File
	file_invoice_invoice_proto_goTypes = nil
	file_invoice_invoice_proto_depIdxs = nil
}
