// Code generated by sdm. DO NOT EDIT.

package invoice

import (
	"time"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type InvoicePii struct {
	InvoiceId string         `gorm:"column:invoice_id;primaryKey"`
	SellerGst string         `gorm:"column:seller_gst"`
	BuyerGst  string         `gorm:"column:buyer_gst"`
	Metadata  datatypes.JSON `gorm:"column:metadata;type:jsonb"`
}

type InvoiceChain struct {
	Key        string    `gorm:"primaryKey;column:key"`
	FieldName  string    `gorm:"primaryKey;column:field_name"`
	Version    int64     `gorm:"primaryKey;column:version;autoIncrement"`
	TxHash     string    `gorm:"column:tx_hash"`
	FieldValue string    `gorm:"column:field_value"`
	CreatedAt  time.Time `gorm:"column:created_at"`
}

type InvoiceView struct {
	InvoiceId       string         `gorm:"column:invoice_id"`
	SellerGst       string         `gorm:"column:seller_gst"`
	HashedSellerGst string         `gorm:"column:hashed_seller_gst"`
	BuyerGst        string         `gorm:"column:buyer_gst"`
	HashedBuyerGst  string         `gorm:"column:hashed_buyer_gst"`
	SellerId        string         `gorm:"column:seller_id"`
	BuyerId         string         `gorm:"column:buyer_id"`
	Amount          int64          `gorm:"column:amount"`
	Metadata        datatypes.JSON `gorm:"column:metadata"`
	Price           datatypes.JSON `gorm:"column:price"`
	TxHash          string         `gorm:"column:tx_hash"`
}

func (InvoicePii) TableName() string   { return "pii_invoices" }
func (InvoiceChain) TableName() string { return "chain_invoices" }
func (InvoiceView) TableName() string  { return "invoices" }

func (c *InvoiceChain) EnsureUnique(tx *gorm.DB) bool {
	var count int64
	err := tx.Model(&InvoiceChain{}).Where("field_name = ? AND field_value = ?", c.FieldName, c.FieldValue).Count(&count).Error
	if err != nil {
		return false
	}
	return count == 0
}
