// Code generated by sdm. DO NOT EDIT.

package invoice

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type InvoiceRepo struct {
	db *gorm.DB
}

func NewInvoiceRepo(db *gorm.DB) *InvoiceRepo {
	return &InvoiceRepo{db: db}
}

func (r *InvoiceRepo) SavePii(ctx context.Context, model *Invoice) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		pii := InvoicePii{
			InvoiceId: model.InvoiceId,
			SellerGst: model.SellerGst,
			BuyerGst:  model.BuyerGst,
			SellerId:  model.SellerId,
			BuyerId:   model.BuyerId,
			Price:     model.Price,
		}
		if err := tx.Create(&pii).Error; err != nil {
			return err
		}
		return nil
	})
}

func (r *InvoiceRepo) SaveChain(ctx context.Context, model *Invoice) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// Save Chain Fields
		compositeKey := fmt.Sprintf("%v", model.InvoiceId)
		// Hash SellerGst
		h_SellerGst := sha256.Sum256([]byte(fmt.Sprintf("%v", model.SellerGst)))
		hashed_SellerGst := hex.EncodeToString(h_SellerGst[:])
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "hashed_seller_gst",
			FieldValue: hashed_SellerGst,
		}).Error; err != nil {
			return err
		}
		// Hash BuyerGst
		h_BuyerGst := sha256.Sum256([]byte(fmt.Sprintf("%v", model.BuyerGst)))
		hashed_BuyerGst := hex.EncodeToString(h_BuyerGst[:])
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "hashed_buyer_gst",
			FieldValue: hashed_BuyerGst,
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "amount",
			FieldValue: fmt.Sprintf("%v", model.Amount),
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "metadata",
			FieldValue: string(model.Metadata),
		}).Error; err != nil {
			return err
		}
		return nil
	})
}

func (r *InvoiceRepo) Save(ctx context.Context, model *Invoice) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		pii := InvoicePii{
			InvoiceId: model.InvoiceId,
			SellerGst: model.SellerGst,
			BuyerGst:  model.BuyerGst,
			SellerId:  model.SellerId,
			BuyerId:   model.BuyerId,
			Price:     model.Price,
		}
		if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&pii).Error; err != nil {
			return err
		}

		// Save Chain Fields
		compositeKey := fmt.Sprintf("%v", model.InvoiceId)
		// Hash SellerGst
		h_SellerGst := sha256.Sum256([]byte(fmt.Sprintf("%v", model.SellerGst)))
		hashed_SellerGst := hex.EncodeToString(h_SellerGst[:])
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "hashed_seller_gst",
			FieldValue: hashed_SellerGst,
		}).Error; err != nil {
			return err
		}
		// Hash BuyerGst
		h_BuyerGst := sha256.Sum256([]byte(fmt.Sprintf("%v", model.BuyerGst)))
		hashed_BuyerGst := hex.EncodeToString(h_BuyerGst[:])
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "hashed_buyer_gst",
			FieldValue: hashed_BuyerGst,
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "amount",
			FieldValue: fmt.Sprintf("%v", model.Amount),
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&InvoiceChain{
			Key:        compositeKey,
			FieldName:  "metadata",
			FieldValue: string(model.Metadata),
		}).Error; err != nil {
			return err
		}
		return nil
	})
}

func (r *InvoiceRepo) Fetch(ctx context.Context, invoiceId string) (*InvoiceView, error) {
	var view InvoiceView
	if err := r.db.WithContext(ctx).Where("invoice_id = ?", invoiceId).Where("is_deleted = ?", false).First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

func (r *InvoiceRepo) Exists(ctx context.Context, invoiceId string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&InvoicePii{}).Where("invoice_id = ?", invoiceId).Where("is_deleted = ?", false).Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}
