// Code generated by sdm. DO NOT EDIT.

package invoice

import "strings"

// pgArrayLiteral serialises a string slice as a PostgreSQL array literal.
// e.g. []string{"A", "B"} → "{A,B}"
// fmt.Sprintf("%v", slice) produces "[A B]" which is NOT valid PostgreSQL —
// this helper produces "{A,B}" which survives a ::text[] cast.
func pgArrayLiteral(vals []string) string {
	return "{" + strings.Join(vals, ",") + "}"
}
