// Code generated by sdm. DO NOT EDIT.

package user

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

type UserRepo struct {
	db *gorm.DB
}

func NewUserRepo(db *gorm.DB) *UserRepo {
	return &UserRepo{db: db}
}

func (r *UserRepo) SavePii(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		pii := UserPii{
			UserId: model.UserId,
			Email:  model.Email,
			Name:   model.Name,
		}
		if err := tx.Create(&pii).Error; err != nil {
			return err
		}
		model.Id = pii.Id // copy DB-generated value back to model
		return nil
	})
}

func (r *UserRepo) SaveChain(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		// Save Chain Fields
		compositeKey := fmt.Sprintf("%v", model.UserId)
		// Hash Email
		h_Email := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
		hashed_Email := hex.EncodeToString(h_Email[:])
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "hashed_email",
			FieldValue: hashed_Email,
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "pan",
			FieldValue: fmt.Sprintf("%v", model.Pan),
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "country",
			FieldValue: fmt.Sprintf("%v", model.Country),
		}).Error; err != nil {
			return err
		}
		return nil
	})
}

func (r *UserRepo) Save(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		pii := UserPii{
			UserId: model.UserId,
			Email:  model.Email,
			Name:   model.Name,
		}
		if err := tx.Clauses(clause.OnConflict{DoNothing: true}).Create(&pii).Error; err != nil {
			return err
		}
		model.Id = pii.Id // copy DB-generated value back to model

		// Save Chain Fields
		compositeKey := fmt.Sprintf("%v", model.UserId)
		// Hash Email
		h_Email := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
		hashed_Email := hex.EncodeToString(h_Email[:])
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "hashed_email",
			FieldValue: hashed_Email,
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "pan",
			FieldValue: fmt.Sprintf("%v", model.Pan),
		}).Error; err != nil {
			return err
		}
		if err := tx.Create(&UserChain{
			Key:        compositeKey,
			FieldName:  "country",
			FieldValue: fmt.Sprintf("%v", model.Country),
		}).Error; err != nil {
			return err
		}
		return nil
	})
}

func (r *UserRepo) Fetch(ctx context.Context, id string) (*UserView, error) {
	var view UserView
	if err := r.db.WithContext(ctx).Where("id = ?", id).First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

func (r *UserRepo) FetchByEmail(ctx context.Context, email string) (*UserView, error) {
	var view UserView
	if err := r.db.WithContext(ctx).Where("email = ?", email).First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

func (r *UserRepo) FetchByPan(ctx context.Context, pan string) (*UserView, error) {
	var view UserView
	if err := r.db.WithContext(ctx).Where("pan = ?", pan).First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

func (r *UserRepo) Exists(ctx context.Context, id string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("id = ?", id).Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

func (r *UserRepo) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("email = ?", email).Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

func (r *UserRepo) ExistsByPan(ctx context.Context, pan string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("pan = ?", pan).Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}
