// Code generated by sdm. DO NOT EDIT.

package user

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"github.com/jackc/pgx/v5/pgconn"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// UserRepo is the data-access handle for User. The actor
// identifier used for audit attribution flows via ctx (see WithActor);
// the repo is stateless and safe for concurrent use by multiple goroutines.
type UserRepo struct {
	db *gorm.DB
}

// NewUserRepo returns a repo bound to db. Pass a *gorm.DB configured
// against the same database the generated schema was applied to. Sharing
// a single *gorm.DB across goroutines is fine — GORM's connection pool
// handles per-call isolation.
func NewUserRepo(db *gorm.DB) *UserRepo {
	return &UserRepo{db: db}
}

// Create inserts a new PII row strictly — PK / unique-index violations
// surface as the driver-native error (e.g. *pgconn.PgError SQLSTATE
// 23505), not an upsert. Auto-increment PKs are copied back onto the
// passed model.
//
// chain-drafts ON: in the same transaction, every chain-stored field
// (and any hashed sidecars) is written as a DRAFTED chain row. Those
// rows are NOT yet visible in the committed view — callers must call
// CommitChain(...) to promote them, or DropChain(...) to discard.
// ErrPendingDraftExists is returned if any chain field already has a
// DRAFTED row for this key.
func (r *UserRepo) Create(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		if _actor != "" {
			if err := tx.Exec("SELECT set_config('sdm.actor', ?, true)", _actor).Error; err != nil {
				return err
			}
		}
		pii := UserPii{
			UserId:    model.UserId,
			Email:     model.Email,
			Name:      model.Name,
			CreatedBy: _actor,
		}
		if err := tx.Create(&pii).Error; err != nil {
			return err
		}
		model.Id = pii.Id // copy DB-generated value back to model
		// chain-drafts: stage chain fields as DRAFTED in the same transaction
		compositeKey := fmt.Sprintf("%v", model.UserId)
		var _latestRows []struct {
			FieldName  string
			FieldValue string
		}
		if err := tx.Raw("SELECT DISTINCT ON (field_name) field_name, field_value FROM chain_users WHERE key = ? AND status = 'CREATED' ORDER BY field_name, version DESC", compositeKey).Scan(&_latestRows).Error; err != nil {
			return err
		}
		_latest := make(map[string]string, len(_latestRows))
		for _, _r := range _latestRows {
			_latest[_r.FieldName] = _r.FieldValue
		}
		{
			// Hash Email
			_h := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
			_hv := hex.EncodeToString(_h[:])
			if _prev, _ok := _latest["hashed_email"]; !_ok || _prev != _hv {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "hashed_email",
					FieldValue: _hv,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Pan)
			if _prev, _ok := _latest["pan"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "pan",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Country)
			if _prev, _ok := _latest["country"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "country",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		return nil
	})
}

// Upsert is the chain-drafts equivalent of SaveAll: PII INSERT on miss
// or UPDATE on conflict against the chain identifier key (mutable
// columns only), followed by DraftChain in the same transaction.
// Chain rows are written as DRAFTED — they are NOT visible in the
// committed view until CommitChain is called. Returns
// ErrPendingDraftExists if any chain field already has a pending
// DRAFTED row for this key.
func (r *UserRepo) Upsert(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		if _actor != "" {
			if err := tx.Exec("SELECT set_config('sdm.actor', ?, true)", _actor).Error; err != nil {
				return err
			}
		}
		pii := UserPii{
			UserId:    model.UserId,
			Email:     model.Email,
			Name:      model.Name,
			CreatedBy: _actor,
		}
		if err := tx.Clauses(clause.OnConflict{
			Columns:   []clause.Column{{Name: "user_id"}},
			DoUpdates: clause.AssignmentColumns([]string{"email", "name", "updated_at"}),
		}).Create(&pii).Error; err != nil {
			return err
		}
		model.Id = pii.Id // copy DB-generated value back to model
		// chain-drafts: stage chain fields as DRAFTED in the same transaction
		compositeKey := fmt.Sprintf("%v", model.UserId)
		var _latestRows []struct {
			FieldName  string
			FieldValue string
		}
		if err := tx.Raw("SELECT DISTINCT ON (field_name) field_name, field_value FROM chain_users WHERE key = ? AND status = 'CREATED' ORDER BY field_name, version DESC", compositeKey).Scan(&_latestRows).Error; err != nil {
			return err
		}
		_latest := make(map[string]string, len(_latestRows))
		for _, _r := range _latestRows {
			_latest[_r.FieldName] = _r.FieldValue
		}
		{
			// Hash Email
			_h := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
			_hv := hex.EncodeToString(_h[:])
			if _prev, _ok := _latest["hashed_email"]; !_ok || _prev != _hv {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "hashed_email",
					FieldValue: _hv,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Pan)
			if _prev, _ok := _latest["pan"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "pan",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Country)
			if _prev, _ok := _latest["country"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "country",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		return nil
	})
}

// Update strictly UPDATEs the PII row (no insert-on-miss — use Upsert
// for that) and stages DRAFTED chain entries for every chain-stored
// field whose value differs from the latest committed value. Only the
// mutable columns are touched; created_by and created_at stay intact.
// Returns gorm.ErrRecordNotFound if the PII row does not exist, or
// ErrPendingDraftExists if any chain field already has a pending
// DRAFTED row for this key.
func (r *UserRepo) Update(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		if _actor != "" {
			if err := tx.Exec("SELECT set_config('sdm.actor', ?, true)", _actor).Error; err != nil {
				return err
			}
		}
		pii := UserPii{
			UserId:    model.UserId,
			Email:     model.Email,
			Name:      model.Name,
			CreatedBy: _actor,
		}
		_result := tx.Model(&UserPii{}).
			Where("user_id = ?", model.UserId).
			Select([]string{"email", "name", "updated_at"}).
			Updates(pii)
		if _result.Error != nil {
			return _result.Error
		}
		if _result.RowsAffected == 0 {
			return gorm.ErrRecordNotFound
		}
		// chain-drafts: stage chain fields as DRAFTED in the same transaction
		compositeKey := fmt.Sprintf("%v", model.UserId)
		var _latestRows []struct {
			FieldName  string
			FieldValue string
		}
		if err := tx.Raw("SELECT DISTINCT ON (field_name) field_name, field_value FROM chain_users WHERE key = ? AND status = 'CREATED' ORDER BY field_name, version DESC", compositeKey).Scan(&_latestRows).Error; err != nil {
			return err
		}
		_latest := make(map[string]string, len(_latestRows))
		for _, _r := range _latestRows {
			_latest[_r.FieldName] = _r.FieldValue
		}
		{
			// Hash Email
			_h := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
			_hv := hex.EncodeToString(_h[:])
			if _prev, _ok := _latest["hashed_email"]; !_ok || _prev != _hv {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "hashed_email",
					FieldValue: _hv,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Pan)
			if _prev, _ok := _latest["pan"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "pan",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Country)
			if _prev, _ok := _latest["country"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "country",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		return nil
	})
}

// DraftChain stages chain edits without touching the PII row. For every
// chain-stored field whose value differs from the latest CREATED entry,
// a new row is appended with Status='DRAFTED'. At most one DRAFTED row
// per (key, field_name) is allowed (enforced by a partial unique
// index); a second draft surfaces ErrPendingDraftExists. For chain-only
// messages this is the primary ingestion path; for PII-backed messages
// it lets callers stage chain edits separately from PII writes.
func (r *UserRepo) DraftChain(ctx context.Context, model *User) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		compositeKey := fmt.Sprintf("%v", model.UserId)
		var _latestRows []struct {
			FieldName  string
			FieldValue string
		}
		if err := tx.Raw("SELECT DISTINCT ON (field_name) field_name, field_value FROM chain_users WHERE key = ? AND status = 'CREATED' ORDER BY field_name, version DESC", compositeKey).Scan(&_latestRows).Error; err != nil {
			return err
		}
		_latest := make(map[string]string, len(_latestRows))
		for _, _r := range _latestRows {
			_latest[_r.FieldName] = _r.FieldValue
		}
		{
			// Hash Email
			_h := sha256.Sum256([]byte(fmt.Sprintf("%v", model.Email)))
			_hv := hex.EncodeToString(_h[:])
			if _prev, _ok := _latest["hashed_email"]; !_ok || _prev != _hv {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "hashed_email",
					FieldValue: _hv,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Pan)
			if _prev, _ok := _latest["pan"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "pan",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		{
			_v := fmt.Sprintf("%v", model.Country)
			if _prev, _ok := _latest["country"]; !_ok || _prev != _v {
				_row := UserChain{
					Key:        compositeKey,
					FieldName:  "country",
					FieldValue: _v,
					CreatedBy:  _actor,
					Status:     "DRAFTED",
				}
				if err := tx.Create(&_row).Error; err != nil {
					var _pg *pgconn.PgError
					if errors.As(err, &_pg) && _pg.Code == "23505" {
						return ErrPendingDraftExists
					}
					return err
				}
			}
		}
		return nil
	})
}

// CommitChain promotes every DRAFTED row for this key to CREATED in a
// single atomic UPDATE and stamps the supplied txHash on the promoted
// rows (pass "" if not applicable). The state-machine BEFORE UPDATE
// trigger guards the DRAFTED → CREATED transition. Idempotent: a no-op
// when no DRAFTED rows exist for the key. After commit, the rows are
// visible from the committed view.
func (r *UserRepo) CommitChain(ctx context.Context, userId string, txHash string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		if _actor != "" {
			if err := tx.Exec("SELECT set_config('sdm.actor', ?, true)", _actor).Error; err != nil {
				return err
			}
		}
		_key := fmt.Sprintf("%v", userId)
		return tx.Model(&UserChain{}).
			Where("key = ? AND status = ?", _key, "DRAFTED").
			Updates(map[string]interface{}{"status": "CREATED", "tx_hash": txHash}).Error
	})
}

// DropChain promotes every DRAFTED row for this key to DROPPED in a
// single UPDATE — discards a pending edit without committing. The
// dropped rows remain in the chain table as audit history; they are
// not visible from either view. Idempotent: no-op when no DRAFTED rows
// exist for the key.
func (r *UserRepo) DropChain(ctx context.Context, userId string) error {
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		_actor := actorFromContext(ctx)
		if _actor != "" {
			if err := tx.Exec("SELECT set_config('sdm.actor', ?, true)", _actor).Error; err != nil {
				return err
			}
		}
		_key := fmt.Sprintf("%v", userId)
		return tx.Model(&UserChain{}).
			Where("key = ? AND status = ?", _key, "DRAFTED").
			Update("status", "DROPPED").Error
	})
}

// Fetch reads the view row keyed by the primary key, scoped to
// non-soft-deleted records (deleted_at IS NULL). Returns
// gorm.ErrRecordNotFound if no row matches.
//
// drafted=true reads from the users_with_drafts overlay view
// (uncommitted DRAFTED values visible); drafted=false reads from the
// committed view. HasPendingDrafts on the result is populated either way.
func (r *UserRepo) Fetch(ctx context.Context, id int64, drafted bool) (*UserView, error) {
	var view UserView
	_table := "users"
	if drafted {
		_table = "users_with_drafts"
	}
	if err := r.db.WithContext(ctx).Table(_table).Where("id = ?", id).Where("deleted_at IS NULL").First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

// FetchByUserId reads the view row by the unique user_id column,
// scoped to non-soft-deleted records. Returns gorm.ErrRecordNotFound if no
// row matches.
// Same drafted-bool semantics as Fetch (overlay vs committed view).
func (r *UserRepo) FetchByUserId(ctx context.Context, userId string, drafted bool) (*UserView, error) {
	var view UserView
	_table := "users"
	if drafted {
		_table = "users_with_drafts"
	}
	if err := r.db.WithContext(ctx).Table(_table).Where("user_id = ?", userId).Where("deleted_at IS NULL").First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

// FetchByEmail reads the view row by the unique email column,
// scoped to non-soft-deleted records. Returns gorm.ErrRecordNotFound if no
// row matches.
// Same drafted-bool semantics as Fetch (overlay vs committed view).
func (r *UserRepo) FetchByEmail(ctx context.Context, email string, drafted bool) (*UserView, error) {
	var view UserView
	_table := "users"
	if drafted {
		_table = "users_with_drafts"
	}
	if err := r.db.WithContext(ctx).Table(_table).Where("email = ?", email).Where("deleted_at IS NULL").First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

// FetchByPan reads the view row by the unique pan column,
// scoped to non-soft-deleted records. Returns gorm.ErrRecordNotFound if no
// row matches.
// Same drafted-bool semantics as Fetch (overlay vs committed view).
func (r *UserRepo) FetchByPan(ctx context.Context, pan string, drafted bool) (*UserView, error) {
	var view UserView
	_table := "users"
	if drafted {
		_table = "users_with_drafts"
	}
	if err := r.db.WithContext(ctx).Table(_table).Where("pan = ?", pan).Where("deleted_at IS NULL").First(&view).Error; err != nil {
		return nil, err
	}
	return &view, nil
}

// Exists reports whether a non-soft-deleted PII row exists for the given
// primary key. Not draft-aware — answered by committed PII state.
func (r *UserRepo) Exists(ctx context.Context, id int64) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("id = ?", id).Where("deleted_at IS NULL").Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

// ExistsByUserId reports whether a non-soft-deleted PII row exists for
// the given user_id value.
func (r *UserRepo) ExistsByUserId(ctx context.Context, userId string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("user_id = ?", userId).Where("deleted_at IS NULL").Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

// ExistsByEmail reports whether a non-soft-deleted PII row exists for
// the given email value.
func (r *UserRepo) ExistsByEmail(ctx context.Context, email string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("email = ?", email).Where("deleted_at IS NULL").Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

// ExistsByPan reports whether a non-soft-deleted PII row exists for
// the given pan value.
func (r *UserRepo) ExistsByPan(ctx context.Context, pan string) (bool, error) {
	var count int64
	if err := r.db.WithContext(ctx).Model(&UserPii{}).Where("pan = ?", pan).Where("deleted_at IS NULL").Count(&count).Error; err != nil {
		return false, err
	}
	return count > 0, nil
}

// AuditLog returns the audit_pii_users history for a single
// record, chronologically (oldest first). Each row is a snapshot of the
// PII row taken immediately BEFORE an UPDATE or DELETE by the AFTER
// trigger; INSERTs do not produce audit rows, so a record that was
// inserted but never modified returns the empty slice. Param signature
// mirrors Fetch — takes the PK; for composite PKs the audit ref_id is
// the PK components joined with ':'.
func (r *UserRepo) AuditLog(ctx context.Context, id int64) ([]UserPiiAudit, error) {
	var rows []UserPiiAudit
	if err := r.db.WithContext(ctx).
		Where("ref_id = ?", fmt.Sprintf("%v", id)).
		Order("changed_at ASC, id ASC").
		Find(&rows).Error; err != nil {
		return nil, err
	}
	return rows, nil
}

// ChangeLog returns the full per-field version history for a single record,
// grouped by field_name then version (1-based, ascending). With
// chain-drafts enabled the result includes rows of every status (DRAFTED
// / CREATED / DROPPED) — filter by status on the returned entries if
// only committed history is wanted. Soft-deleted PII rows do NOT mask
// chain history (chain entries persist independently). Returns
// gorm.ErrRecordNotFound when no chain rows exist for the key. Param
// signature mirrors Create — takes the chain identifier key field(s).
func (r *UserRepo) ChangeLog(ctx context.Context, userId string) (ChangeLog, error) {
	var rows []UserChain
	if err := r.db.WithContext(ctx).
		Where("key = ?", fmt.Sprintf("%v", userId)).
		Order("field_name, version").
		Find(&rows).Error; err != nil {
		return nil, err
	}
	if len(rows) == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	log := make(ChangeLog)
	for _, row := range rows {
		if _, ok := log[row.FieldName]; !ok {
			log[row.FieldName] = make(map[int64]ChangeLogEntry)
		}
		log[row.FieldName][row.Version] = ChangeLogEntry{
			Value:     row.FieldValue,
			Timestamp: row.CreatedAt,
		}
	}
	return log, nil
}
