// Code generated by sdm. DO NOT EDIT.

package user

import (
	"time"
	"gorm.io/gorm"
)

type UserPii struct {
	Id     int64  `gorm:"column:id;primaryKey;autoIncrement"`
	UserId string `gorm:"column:user_id;uniqueIndex"`
	Email  string `gorm:"column:email;uniqueIndex"`
	Name   string `gorm:"column:name"`
}

type UserChain struct {
	Key        string    `gorm:"primaryKey;column:key"`
	FieldName  string    `gorm:"primaryKey;column:field_name"`
	Version    int64     `gorm:"primaryKey;column:version;autoIncrement"`
	TxHash     string    `gorm:"column:tx_hash"`
	FieldValue string    `gorm:"column:field_value"`
	CreatedAt  time.Time `gorm:"column:created_at"`
}

type UserView struct {
	Id          int64  `gorm:"column:id"`
	UserId      string `gorm:"column:user_id"`
	Email       string `gorm:"column:email"`
	HashedEmail string `gorm:"column:hashed_email"`
	Name        string `gorm:"column:name"`
	Pan         string `gorm:"column:pan"`
	Country     string `gorm:"column:country"`
	TxHash      string `gorm:"column:tx_hash"`
}

func (UserPii) TableName() string   { return "pii_users" }
func (UserChain) TableName() string { return "chain_users" }
func (UserView) TableName() string  { return "users" }

func (c *UserChain) EnsureUnique(tx *gorm.DB) bool {
	var count int64
	err := tx.Model(&UserChain{}).Where("field_name = ? AND field_value = ?", c.FieldName, c.FieldValue).Count(&count).Error
	if err != nil {
		return false
	}
	return count == 0
}
